/**
 * Service to export deadlines into iCal (.ics), Markdown, and Print formats.
 */

// Format date to iCal UTC format: YYYYMMDDTHHMMSSZ
function formatDateToICS(isoString) {
  const date = new Date(isoString);
  if (isNaN(date.getTime())) {
    const now = new Date();
    return now.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  }
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

/**
 * Generate RFC 5545 compliant .ics calendar string
 */
export function generateICSContent(data) {
  const { courseName, assignments = [] } = data;
  const nowStr = formatDateToICS(new Date().toISOString());

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//ChronoScribe AI//Student Workspace//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${courseName || 'Student Deadlines'} - Study Schedule`,
    'X-WR-TIMEZONE:UTC'
  ];

  assignments.forEach((item) => {
    const dueFormatted = formatDateToICS(item.dueDate);
    // End date 1 hour later
    const dueDateObj = new Date(item.dueDate);
    const endDateObj = new Date(dueDateObj.getTime() + 60 * 60 * 1000);
    const endFormatted = formatDateToICS(endDateObj.toISOString());

    const milestoneList = (item.milestones || [])
      .map((m, idx) => `  [ ] Step ${idx + 1}: ${m.title} (${m.hours}h)`)
      .join('\\n');

    const description = `${item.description || ''}\\n\\nMilestone Checklist:\\n${milestoneList}\\n\\nWeight: ${item.weight || 0}% | Est. Workload: ${item.estimatedHours || 0}h`;

    icsContent.push(
      'BEGIN:VEVENT',
      `UID:${item.id || Date.now()}-${Math.random().toString(36).substring(7)}@chronoscribe.ai`,
      `DTSTAMP:${nowStr}`,
      `DTSTART:${dueFormatted}`,
      `DTEND:${endFormatted}`,
      `SUMMARY:[${item.type?.toUpperCase() || 'DEADLINE'}] ${item.title}`,
      `DESCRIPTION:${description}`,
      `CATEGORIES:ACADEMIC,${item.type || 'ASSIGNMENT'}`,
      'STATUS:CONFIRMED',
      'BEGIN:VALARM',
      'TRIGGER:-P1D', // 1 day before alarm
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${item.title} due in 24 hours!`,
      'END:VALARM',
      'BEGIN:VALARM',
      'TRIGGER:-P3D', // 3 days before alarm
      'ACTION:DISPLAY',
      `DESCRIPTION:Study Checkpoint: 3 days until ${item.title}`,
      'END:VALARM',
      'END:VEVENT'
    );
  });

  icsContent.push('END:VCALENDAR');
  return icsContent.join('\r\n');
}

/**
 * Trigger download of .ics file
 */
export function downloadICS(data) {
  const icsString = generateICSContent(data);
  const blob = new Blob([icsString], { type: 'text/calendar;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const filename = `${(data.courseName || 'deadlines').toLowerCase().replace(/[^a-z0-9]/g, '_')}_schedule.ics`;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate Markdown summary for exporting to Notion, Obsidian, or GitHub
 */
export function generateMarkdownExport(data) {
  const { courseName, instructor, term, assignments = [], studyPlan = [], totalWorkloadHours } = data;

  let md = `# 🎓 ${courseName || 'Course Schedule & Action Plan'}\n`;
  md += `**Instructor:** ${instructor || 'N/A'} | **Term:** ${term || 'N/A'}\n`;
  md += `**Total Estimated Workload:** ${totalWorkloadHours || 'N/A'} hours\n\n`;

  md += `## ⏳ Critical Deadlines & Deliverables\n\n`;
  md += `| Type | Deliverable | Due Date | Weight | Est. Hours | Urgency |\n`;
  md += `| :--- | :--- | :--- | :---: | :---: | :---: |\n`;

  assignments.forEach((a) => {
    const formattedDate = new Date(a.dueDate).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
    md += `| ${a.type} | **${a.title}** | ${formattedDate} | ${a.weight ? a.weight + '%' : '-'} | ${a.estimatedHours || '-'}h | ${a.urgency} |\n`;
  });

  md += `\n## 📝 Decomposed Action Milestones\n\n`;
  assignments.forEach((a) => {
    md += `### ${a.title} (${a.type} - Due: ${new Date(a.dueDate).toLocaleDateString()})\n`;
    if (a.description) md += `*${a.description}*\n\n`;
    (a.milestones || []).forEach((m) => {
      md += `- [ ] **${m.title}** (${m.hours} hrs)\n`;
    });
    md += `\n`;
  });

  if (studyPlan && studyPlan.length > 0) {
    md += `## 🚀 Weekly Study Roadmap\n\n`;
    studyPlan.forEach((week) => {
      md += `### Week ${week.weekNumber}: ${week.theme} (~${week.targetHours}h)\n`;
      md += `**Key Focus:** ${week.focusItems.join(', ')}\n`;
      (week.tasks || []).forEach((t) => {
        md += `- **${t.day}:** ${t.activity} *(${t.duration})*\n`;
      });
      md += `\n`;
    });
  }

  md += `---\n*Generated by ChronoScribe AI - Google for Developers PROMPT WARS*`;
  return md;
}
